### ISSUE TITLE
Better way to include config.php

### ISSUE THREAD

**Issue by mudrd8mz** [moodleuulm/moodle-tool_opcache#1]
There are two minor things with including the config.php like this
```
require_once(dirname(__FILE__).'/../../../config.php');
```
1. The config.php should be included via `require()` not `require_once()`
2. Better to use `__DIR__` and save one function call

Please refer to https://docs.moodle.org/dev/Coding_style#Require_.2F_include

**Comment by abias** [comment]
Thanks for this hint - fixed in 5403d5821cf801c3a4fa9f12183cf5621e4d9928
