### ISSUE TITLE
Include a CDN-less version of opcache-gui

### ISSUE THREAD

**Issue by abias** [moodleuulm/moodle-tool_opcache#10]
opcache-gui, unfortunately, loads scripts from a CDN (see https://github.com/amnuts/opcache-gui/blob/master/index.php#L511-L513). This is not only a data protection issue, it can also break the tool as a whole (see https://github.com/amnuts/opcache-gui/issues/93).

It would be worthwhile to include a CDN-less version of opcache-gui into this plugin.

**Comment by amnuts** [comment]
As of a version [3.4.0](https://github.com/amnuts/opcache-gui/releases/tag/3.4.0) (released early August), you can have the js downloaded and run from the same server, thereby not making it a data protection issue (for opcache-gui, maybe still for this plugin).

It requires you to rebuild the interface, which is just one or two commands, but you'll then have the interface with no external dependencies.

For more info, see: https://github.com/amnuts/opcache-gui#the-javascript

If the options in opcache-gui don't work for what you need, then I'm open to any suggestions for improvements!

**Comment by abias** [comment]
Thank you very much for this very important hint and helpful feature!
I have just added a CDN-less version of opcache-gui to this plugin here and will publish a new release soon.

Cheers,
Alex
