### ISSUE TITLE
Excepción - array_diff_key():

### ISSUE THREAD

**Issue by ghost** [moodleuulm/moodle-tool_opcache#11]
Hi, When accessing the administration menu and pressing the opcahe tool button, this error is displayed:
Excepción - array_diff_key(): Argument #2 must be of type array, null given
Regards

**Comment by melanietreitinger** [comment]
Which Moodle version and which plugin version do you use?

**Comment by ghost** [comment]
Hi, sorry for this ;)
tool_opcache ver. v4.0-r2
oodle ver. Versión 4.1.1 (Build: 20230116)

Warning: Warning: Trying to access array offset on value of type bool in /home/acceso25/www/admin/tool/opcache/lib/opcache-gui/index.php.inc on line 337

`    protected function compileState(): array
    {
        $status = opcache_get_status();
        $config = opcache_get_configuration();
        $missingConfig = array_diff_key(ini_get_all('zend opcache', false), $config['directives']);
        if (!empty($missingConfig)) {
            $config['directives'] = array_merge($config['directives'], $missingConfig);
        }`
I always have this alert: Warning: Zend OPcache API is restricted by "restrict_api" configuration directive in

THX

**Comment by melanietreitinger** [comment]
Please check your `php.ini` for the following entry:
`opcache.restrict_api=1`

If the value is set to `1`, please change this to (without the `1`):
`opcache.restrict_api=`

After that, restart Apache (and php-fpm if you use this).

See https://www.php.net/manual/en/opcache.configuration.php#ini.opcache.restrict-api.

This should solve your issue.

**Comment by ghost** [comment]
Hi, I have it set like this `opcache.restrict_api=` and I have restarted apache and php-fpm, but it doesn't work

**Comment by abias** [comment]
Hi @nukuaes ,

I had a look at the error message which you have posted.
You wrote that the error is thrown in /home/acceso25/www/admin/tool/opcache/lib/opcache-gui/index.php.inc.
You have to know that this plugin is just a wrapper around another piece of software, opcache-gui by Andrew Collington. And this index.php file is Andrew's software.

I would like to ask you for two things:

1. Please go to https://github.com/amnuts/opcache-gui, checkout the repo to your webserver and call index.php in the browser. In this case, you will use the same software as in this Moodle plugin, just without the Moodle wrapper. If you encounter the same error there as well, please create an issue in Andrew's repo and tell him about it.

2. If you do not encounter the error there, please be patient. We just update the opcache-gui in this plugin from time to time. There will be a new release of this plugin soon with the latest version of opcache-gui included. In this case, I hope that the error will be gone for you as well.

Cheers,
Alex

**Comment by abias** [comment]
PS: Please forget the second point. There isn't any new version of opcache-gui, i.e. this plugin already contains the latest version.
