### ISSUE TITLE
No need to run Travis on both databases

### ISSUE THREAD

**Issue by mudrd8mz** [moodleuulm/moodle-tool_opcache#2]
As far as I can see, the plugin does not use the Moodle database at all. It feels like wasting Travis' resources to run the checks against both MySQL and PostgreSQL in this case.

Please help global climate and do not let cloud servers burn energy for what is not really needed.

If you agree and fix this, please feel encouraged to report back at https://tracker.moodle.org/browse/MDL-15169 :-)

**Comment by abias** [comment]
You are completely right about that - fixed in 9cb6d7497a2c4843441feb85327eee1e32864c4c
