### ISSUE TITLE
Breadcrumb navbar appearance is messed up - vertical offset of menu items

### ISSUE THREAD

**Issue by bollycanuk** [moodleuulm/moodle-tool_opcache#3]
Installed the latest version of Opcache (v3.6-r1 (2019020100)Moodle 3.6) and while it works OK, the appearance of the breadcrumb navbar is corrupted.

Running Moodle 3.6.2 with lateset version of Fordson theme (Moodle 3.6 Fordson v3.6 release 1.2 (2019111001))

[AJOLT environment.pdf](https://github.com/moodleuulm/moodle-tool_opcache/files/2821847/AJOLT.environment.pdf)

![opcache breadcrumb distortion 20190201](https://user-images.githubusercontent.com/9040146/52127122-3229d000-25ff-11e9-94f9-9c4d7fcc0409.PNG)

**Comment by abias** [comment]
Hi Derek,

thank you for posting this issue.

May I ask you if you have installed tool_opcache from scratch or if you have upgraded it from the 3.5 version? There hasn't been any functional change from 3.5 to 3.6, but I am just asking to be sure.

On the Boost theme, I don't see any flaws with the breadcrumb at first sight. Fordson is based on Boost, but it does several things differently, for example the breadcrumb bar. 

I would love to ping @kennybc who created Fordson, but this seems to be impossible as he isn't a participant of this Github repo. Perhaps you might want to cross-post this issue at https://github.com/dbnschools/moodle-theme_fordson/issues to get his feedback.

**Comment by abias** [comment]
As there wasn't any feedback anymore, I will close this issue now.
