### ISSUE TITLE
Interned Strings Buffer - showing different value

### ISSUE THREAD

**Issue by mruasar** [moodleuulm/moodle-tool_opcache#6]
I dont know if this is even an issue
![interned](https://user-images.githubusercontent.com/5184754/87213872-a662ba00-c341-11ea-8e3e-76eec3d1579b.jpg)

Moodle 3.7
plug-in 3.7r-1
entered 32MB, showing 24MB

Interned Strings Buffer value is showing differently, was showing accurate in moodle 3.5 and plug-in 3.5r-1

**Comment by abias** [comment]
Hey @mruasar ,

thank you for creating this issue and sorry for the delay to get back to you.

I am sorry to say that I can't do anything about your issue. This Moodle plugin is just embedding an external tool which is developed and hosted by another developer. I would like to ask you to turn to https://github.com/amnuts/opcache-gui/issues to discuss your issue.

Cheers,
Alex
