### ISSUE TITLE
opcache gui does not show up

### ISSUE THREAD

**Issue by KaiNieLC** [moodleuulm/moodle-tool_opcache#7]
Hi there,
I have a moodle site with opcache enabled in PHP and your plugin installed in the latest version.
However the gui that you present on the moodle plugin site does not show up. Instead I only see tabs and the available functions
--
opcache_reset
opcache_invalidate
opcache_compile_file
opcache_is_script_cached
opcache_get_configuration
opcache_get_status

How can I get the opcache overview displayed?

**Comment by abias** [comment]
Hey @snack753 ,

basically, this plugin just wraps a nice third-party tool from Andrew Collington into a Moodle plugin.

If the plugin is shown in the Moodle site administration and you see at least _something_ on the Site administration -> Server -> Opcache management page, I would say that the plugin is working.

Regarding problems with Opcache-GUI itself, I would like to propose that you try multiple and contenporary browsers first (as it is using relatively new JavaScript code syntax) and then redirect problems together with some screenshots to Andrew on https://github.com/amnuts/opcache-gui/issues. 

Cheers,
Alex
